# Generated by Django 2.1.2 on 2018-11-23 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0002_auto_20181123_1424'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HiddenRequests',
            new_name='HiddenRequest',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
