# Generated by Django 2.1.2 on 2018-11-23 14:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0003_auto_20181123_1500'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportedRequests',
            new_name='ReportedRequest',
        ),
    ]
